"""Deterministic heuristic analyzer for the Stage 1 baseline.

Orchestrates specialized semantic detectors for goal, decision, constraint,
architecture, tech-stack, and roadmap detection.
"""

from __future__ import annotations

import re
from pathlib import Path

from contextix.models import AnalysisResult, ContextIR, ParsedDocument, ProjectIdentity

from .detectors import (
    ArchitectureDetector,
    ConstraintDetector,
    DecisionDetector,
    GoalDetector,
    RoadmapDetector,
    TechStackDetector,
    extract_section,
    extract_bullets,
)


class BasicAnalyzer:
    """Extract initial project understanding without using an LLM.

    Delegates to specialized detectors for each semantic category.
    """

    def __init__(self) -> None:
        self._goal_detector = GoalDetector()
        self._decision_detector = DecisionDetector()
        self._constraint_detector = ConstraintDetector()
        self._architecture_detector = ArchitectureDetector()
        self._techstack_detector = TechStackDetector()
        self._roadmap_detector = RoadmapDetector()

    def analyze(self, documents: list[ParsedDocument], root: Path) -> ContextIR:
        readme = self._find_document(documents, "README.md")
        project_name = self._project_name(readme, root)
        description = self._description(readme)

        result = AnalysisResult(
            project=ProjectIdentity(name=project_name, description=description),
            vision=(
                self._extract_section(readme, "Long-Term Vision")
                or self._extract_manifest_vision(documents)
            ),
            goals=self._goal_detector.detect(documents),
            tech_stack=self._techstack_detector.detect(documents),
            architecture=self._architecture_detector.detect(documents),
            architecture_patterns=self._architecture_detector.detect_patterns(documents),
            constraints=self._constraint_detector.detect(documents),
            non_goals=self._extract_bullets(documents, ["Non-Goals", "Out of Scope"]),
            features=self._extract_bullets(documents, ["Features", "MVP Scope", "Functional Requirements"]),
            decisions=self._decision_detector.detect(documents),
            roadmap=self._roadmap_detector.detect(documents),
            coding_standards=self._extract_bullets(documents, ["Coding Principles", "CLI Principles"]),
            documentation=sorted(doc.source for doc in documents if doc.file_type == "markdown"),
            completed=["Stage 0 documentation baseline exists"],
            current=["Stage 1 MVP foundation"],
            next=["Improve parser coverage", "Add PDF parser", "Add richer validation"],
            issues=["Heuristic analysis can miss implicit project knowledge"],
        )

        return ContextIR(**result.__dict__)

    def _find_document(self, documents: list[ParsedDocument], source: str) -> ParsedDocument | None:
        return next((doc for doc in documents if doc.source.lower() == source.lower()), None)

    def _project_name(self, readme: ParsedDocument | None, root: Path) -> str:
        if readme:
            match = re.search(r"^#\s+(.+)$", readme.content, re.MULTILINE)
            if match:
                return match.group(1).strip()
        return root.name

    def _description(self, readme: ParsedDocument | None) -> str:
        if not readme:
            return "Project memory generated by Contextix."

        for line in readme.content.splitlines():
            stripped = line.strip()
            if stripped and not stripped.startswith("#") and not stripped.startswith(">"):
                return stripped

        return "Project memory generated by Contextix."

    def _extract_manifest_vision(self, documents: list[ParsedDocument]) -> str:
        manifest = self._find_document(documents, "MANIFESTO.md")
        return self._extract_section(manifest, "Our Vision")

    def _extract_section(self, document: ParsedDocument | None, heading: str) -> str:
        if not document:
            return ""
        return extract_section(document.content, heading)

    def _extract_bullets(self, documents: list[ParsedDocument], headings: list[str]) -> list[str]:
        from .detectors.shared import deduplicate_preserve_order

        values: list[str] = []
        for doc in documents:
            for heading in headings:
                section = self._extract_section(doc, heading)
                values.extend(extract_bullets(section))
        return deduplicate_preserve_order(values)